framework:
    default_locale: 'ir'
    translator:
#        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['en','fa']
        paths:
            - "%kernel.project_dir%/translations/fa/accounting"
            - "%kernel.project_dir%/translations/en/accounting"
